<?php

namespace Bordeux\Bundle\FileBundle\Repository;

/**
 * StorageParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StorageParameterRepository extends \Doctrine\ORM\EntityRepository
{
}
